### ISSUE TITLE
latest docker does not appear to work

### ISSUE THREAD

**Issue by sbade1** [eclecticiq/OpenTAXII#100]
I've pulled down the latest docker from docker.io (eclecticiq/opentaxii:latest).
Using a opentaxi.yml (and services.yml and collections.yml files) that works fine with version 0.1.9,  when I use the cappy command line to push content, i get unauthorized.  On 0.1.9 I can do any of the cappy cli command tools.   
```
taxii-discovery --host localhost --port 9000 --path /services/discovery returns

 taxii-discovery --host localhost --port 9000 --path /services/discovery
2018-02-26 17:34:13,923 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-26 17:34:13,956 INFO: 4 services discovered
=== Service Instance ===
  Service Type: INBOX
  Service Version: urn:taxii.mitre.org:services:1.1
  Protocol Binding: urn:taxii.mitre.org:protocol:http:1.0
  Service Address: http://0.0.0.0:9000/services/inbox
  Message Binding: urn:taxii.mitre.org:message:xml:1.0
  Message Binding: urn:taxii.mitre.org:message:xml:1.1
  Inbox Service AC: []
  Available: True
  Message: Custom Inbox Service Description A

=== Service Instance ===
  Service Type: DISCOVERY
  Service Version: urn:taxii.mitre.org:services:1.1
  Protocol Binding: urn:taxii.mitre.org:protocol:http:1.0
  Service Address: http://0.0.0.0:9000/services/discovery
  Message Binding: urn:taxii.mitre.org:message:xml:1.0
  Message Binding: urn:taxii.mitre.org:message:xml:1.1
  Available: True
  Message: Custom Discovery Service description

=== Service Instance ===
  Service Type: COLLECTION_MANAGEMENT
  Service Version: urn:taxii.mitre.org:services:1.1
  Protocol Binding: urn:taxii.mitre.org:protocol:http:1.0
  Service Address: http://0.0.0.0:9000/services/collection-management
  Message Binding: urn:taxii.mitre.org:message:xml:1.0
  Message Binding: urn:taxii.mitre.org:message:xml:1.1
  Available: True
  Message: Custom Collection Management Service description

=== Service Instance ===
  Service Type: POLL
  Service Version: urn:taxii.mitre.org:services:1.1
  Protocol Binding: urn:taxii.mitre.org:protocol:http:1.0
  Service Address: http://0.0.0.0:9000/services/poll
  Message Binding: urn:taxii.mitre.org:message:xml:1.0
  Message Binding: urn:taxii.mitre.org:message:xml:1.1
  Available: True
  Message: Custom Poll Service description
```

doing 
```
taxii-push --host localhost --port 9000  --discovery /services/discovery --content-file ./tests/foo.xml --dest collection
2018-02-26 17:35:22,898 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-26 17:35:22,944 INFO: 4 services discovered
2018-02-26 17:35:22,945 INFO: Sending Inbox_Message to http://0.0.0.0:9000/services/inbox
2018-02-26 17:35:22,984 ERROR: UNAUTHORIZED:
```

**Comment by arcsector** [comment]
Please provide docker and OS info, as well as which cabby version you're using in the opentaxii responses that you posted.

In addition, **please format your response**. It looks terrible when everything is just text. Use a code block.

Thank you. It also seems like your issue was stopped short. Not really sure which response is on which opentaxii version.

**Comment by traut** [comment]
@sbade1 I've formatted your message. Please use Markdown's code block next time for posting snippets of code, logs or error messages.

As about your issue:
- please clarify which response is which opentaxii version
- please post full opentaxii server log for both versions

thanks!

**Comment by sbade1** [comment]
My apologies for the formatting
Docker Version Docker version 17.09.1-ce, build 19e2cf6
Cabby Version 0.1.18
OS - OSX High Sierra

Something very strange this morning.  When going to copy the outputs into the formatting. 

opentaxii docker 0.1.9
```
taxii-push --host localhost --port 9000  --discovery /services/discovery --content-file ./tests/foo.xml --dest collection
2018-02-26 17:37:58,172 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-26 17:37:58,209 INFO: 4 services discovered
2018-02-26 17:37:58,211 INFO: Sending Inbox_Message to http://0.0.0.0:9000/services/inbox
2018-02-26 17:37:58,437 INFO: Content block successfully pushed
taxii-push --host localhost --port 9000  --discovery /services/discovery --content-file ./tests/foo.xml --dest collection
2018-02-26 17:37:58,172 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-26 17:37:58,209 INFO: 4 services discovered
2018-02-26 17:37:58,211 INFO: Sending Inbox_Message to http://0.0.0.0:9000/services/inbox
2018-02-26 17:37:58,437 INFO: Content block successfully pushed
```

Remove the auth.db and data.db from the inputs volume that is mapped (to ensure a clean environment.
Start docker latest.  New auth.db and data.db files are created in /data
```
taxii-push --host localhost --port 9000  --discovery /services/discovery --content-file ./tests/foo.xml --dest collection
2018-02-27 08:30:01,784 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-27 08:30:01,884 ERROR: Can not autodiscover advertised services
2018-02-27 08:30:01,885 ERROR: HTTP Error: status code 404
```
Replace with the auth.db and data.db that was from the 0.1.9 version of the docker image.  The push works fine. Per below
```
taxii-push --host localhost --port 9000  --discovery /services/discovery --content-file ./tests/foo.xml --dest collection
2018-02-27 08:38:15,457 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-27 08:38:15,496 INFO: 4 services discovered
2018-02-27 08:38:15,498 INFO: Sending Inbox_Message to http://0.0.0.0:9000/services/inbox
2018-02-27 08:38:15,649 INFO: Content block successfully pushed
```
Last evening taxii-push to the docker latest image
```
taxii-push --host localhost --port 9000 --discovery /services/discovery --content-file ./tests/foo.xml --dest collection
2018-02-26 17:35:22,898 INFO: Sending Discovery_Request to http://localhost:9000/services/discovery
2018-02-26 17:35:22,944 INFO: 4 services discovered
2018-02-26 17:35:22,945 INFO: Sending Inbox_Message to http://0.0.0.0:9000/services/inbox
2018-02-26 17:35:22,984 ERROR: UNAUTHORIZED:
```

I'm not sure what this would indicate.  I'll try bringing the docker images over to a Centos 7 OS and see what happens with a complete default configuration

**Comment by sbade1** [comment]
on my centos7 linux system, 
docker version
```
Client:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64

Server:
 Version:         1.12.6
 API version:     1.24
 Package version: docker-1.12.6-71.git3e8e77d.el7.centos.1.x86_64
 Go version:      go1.8.3
 Git commit:      3e8e77d/1.12.6
 Built:           Tue Jan 30 09:17:00 2018
 OS/Arch:         linux/amd64
```
if i start the container with
```
docker run -it -p 9000:9000 --name opentaxii -v /home/sbade/otaxii/data:/data -v /home/sbade/otaxii/input:/input eclecticiq/opentaxii:latest
```
the output is
```
Using config:
---

domain: "localhost:9000"

persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: sqlite:////data/data.db
    create_tables: yes

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters:
    db_connection: sqlite:////data/auth.db
    create_tables: yes
    secret: notVerySecret

logging:
  opentaxii: info
  root: info

hooks:
2018-02-27 14:36:07,202 CRIT Supervisor running as root (no user in config file)
2018-02-27 14:36:07,205 INFO supervisord started with pid 1
2018-02-27 14:36:08,209 INFO spawned: 'opentaxii' with pid 10
2018-02-27 14:36:08,373 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:08 +0000] [10] [INFO] Starting gunicorn 19.7.1
[2018-02-27 14:36:08 +0000] [10] [INFO] Listening at: http://0.0.0.0:9000 (10)
[2018-02-27 14:36:08 +0000] [10] [INFO] Using worker: sync

2018-02-27 14:36:08,376 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:08 +0000] [15] [INFO] Booting worker with pid: 15

2018-02-27 14:36:08,459 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:08 +0000] [18] [INFO] Booting worker with pid: 18

2018-02-27 14:36:08,806 DEBG 'opentaxii' stdout output:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run

2018-02-27 14:36:08,808 DEBG 'opentaxii' stdout output:
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run

2018-02-27 14:36:08,809 DEBG 'opentaxii' stdout output:
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in run

2018-02-27 14:36:08,813 DEBG 'opentaxii' stdout output:
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

2018-02-27 14:36:08,826 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140364804528032 for <Subprocess at 140364804471768 with name opentaxii in state STARTING> (stdout)>
2018-02-27 14:36:08,826 INFO exited: opentaxii (exit status 1; not expected)
2018-02-27 14:36:08,826 DEBG received SIGCLD indicating a child quit
2018-02-27 14:36:09,828 INFO spawned: 'opentaxii' with pid 21
2018-02-27 14:36:09,971 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:09 +0000] [21] [INFO] Starting gunicorn 19.7.1
[2018-02-27 14:36:09 +0000] [21] [INFO] Listening at: http://0.0.0.0:9000 (21)
[2018-02-27 14:36:09 +0000] [21] [INFO] Using worker: sync

2018-02-27 14:36:09,975 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:09 +0000] [26] [INFO] Booting worker with pid: 26

2018-02-27 14:36:10,024 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:10 +0000] [29] [INFO] Booting worker with pid: 29

2018-02-27 14:36:10,490 DEBG 'opentaxii' stdout output:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

2018-02-27 14:36:10,512 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140364816804104 for <Subprocess at 140364804471768 with name opentaxii in state STARTING> (stdout)>
2018-02-27 14:36:10,512 INFO exited: opentaxii (exit status 1; not expected)
2018-02-27 14:36:10,512 DEBG received SIGCLD indicating a child quit
2018-02-27 14:36:12,516 INFO spawned: 'opentaxii' with pid 32
2018-02-27 14:36:12,651 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:12 +0000] [32] [INFO] Starting gunicorn 19.7.1

2018-02-27 14:36:12,653 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:12 +0000] [32] [INFO] Listening at: http://0.0.0.0:9000 (32)
[2018-02-27 14:36:12 +0000] [32] [INFO] Using worker: sync

2018-02-27 14:36:12,656 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:12 +0000] [37] [INFO] Booting worker with pid: 37

2018-02-27 14:36:12,687 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:12 +0000] [40] [INFO] Booting worker with pid: 40

2018-02-27 14:36:13,042 DEBG 'opentaxii' stdout output:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

2018-02-27 14:36:13,056 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140364816802232 for <Subprocess at 140364804471768 with name opentaxii in state STARTING> (stdout)>
2018-02-27 14:36:13,056 INFO exited: opentaxii (exit status 1; not expected)
2018-02-27 14:36:13,056 DEBG received SIGCLD indicating a child quit
2018-02-27 14:36:16,062 INFO spawned: 'opentaxii' with pid 43
2018-02-27 14:36:16,202 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:16 +0000] [43] [INFO] Starting gunicorn 19.7.1
[2018-02-27 14:36:16 +0000] [43] [INFO] Listening at: http://0.0.0.0:9000 (43)
[2018-02-27 14:36:16 +0000] [43] [INFO] Using worker: sync

2018-02-27 14:36:16,207 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:16 +0000] [48] [INFO] Booting worker with pid: 48

2018-02-27 14:36:16,301 DEBG 'opentaxii' stdout output:
[2018-02-27 14:36:16 +0000] [51] [INFO] Booting worker with pid: 51

2018-02-27 14:36:16,634 DEBG 'opentaxii' stdout output:
Traceback (most recent call last):
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 231, in run
    self.halt(reason=inst.reason, exit_status=inst.exit_status)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 344, in halt
    self.stop()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 393, in stop
    time.sleep(0.1)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 244, in handle_chld
    self.reap_workers()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 524, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>

2018-02-27 14:36:16,648 DEBG fd 6 closed, stopped monitoring <POutputDispatcher at 140364816804104 for <Subprocess at 140364804471768 with name opentaxii in state STARTING> (stdout)>
2018-02-27 14:36:16,648 INFO exited: opentaxii (exit status 1; not expected)
2018-02-27 14:36:16,648 DEBG received SIGCLD indicating a child quit
2018-02-27 14:36:17,649 INFO gave up: opentaxii entered FATAL state, too many start retries too quickly
```

if i don't mount any volumes, any cabby cli operation gives a 404

**Comment by traut** [comment]
docker script was updated and image re-created after 0.1.10 release. is this issue still reproducible?
