### ISSUE TITLE
STIX Packages fail with json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by packet-rat** [eclecticiq/OpenTAXII#101]
We're attempting to test OpenTAXII with MISP.  99.9% of our standard STIX test packages fail.  Many of these STIX have been successfully used for years to test various STIX/TAXII implementations.  

We can't share these but have replicated the issues with https://github.com/STIXProject/schemas/tree/master/samples and US_CERT/DHS STIX libraries.

STIX Validator and Ramrod are not revealing any clues...

```
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
Here's a representative example using the Mandiant APT 1 - Appendix_G_IOCs_Full.xml 

```

taxii-push --path http://localhost:9000/services/inbox         --dest collection --username taxii  --password BoVLjgTg2om6zJc6CN7g7OHK  -f Appendix_G_IOCs_Full.xml 
2018-04-01 19:51:35,066 INFO: Sending Inbox_Message to http://localhost:9000/services/inbox
2018-04-01 19:51:35,472 ERROR: FAILURE: There was a failure while executing the message handler
```
```
'dGF4aWk6Qm9WTGpnVGcyb202ekpjNkNON2c3T0hL' 40
Posting STIX...
2018-04-01T19:51:35.463453Z [opentaxii.middleware] warning: Status exception {exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg/misp_stix_converter/converters/convert.py", line 109, in load_stix
    stix_package = STIXPackage.from_json(data)
  File "/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/entities.py", line 495, in from_json
    d = json.loads(json_doc)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py", line 83, in process
    response_message = handler.handle_message(self, message)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 65, in handle_message
    inbox_message_id=inbox_message.id if inbox_message else None)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/persistence/manager.py", line 164, in create_content
    collection_ids=collection_ids, service_id=service_id)
  File "/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/misp_taxii_hooks-0.2-py3.5.egg/misp_taxii_hooks/hooks.py", line 62, in post_stix
    package = pymisp.tools.stix.load_stix(StringIO(block))
  File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.89-py3.5.egg/pymisp/tools/stix.py", line 16, in load_stix
    stix = convert.load_stix(stix)
  File "/usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg/misp_stix_converter/converters/convert.py", line 116, in load_stix
    stixXml = etree.parse(stix)
  File "src/lxml/etree.pyx", line 3426, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1856, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
  File "<string>", line 1085
lxml.etree.XMLSyntaxError: Couldn't find end of Start Tag Prope line 1085, line 1085, column 33

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.12.2-py3.5.egg/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/dist-packages/Flask-0.12.2-py3.5.egg/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/middleware.py", line 76, in wrapper
    return _process_with_service(service)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/middleware.py", line 154, in _process_with_service
    response_message = service.process(request.headers, taxii_message)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py", line 89, in process
    in_response_to=message.message_id)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/exceptions.py", line 48, in raise_failure
    tb=tb)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/abstract.py", line 83, in process
    response_message = handler.handle_message(self, message)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 126, in handle_message
    return InboxMessage11Handler.handle_message(service, request)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/taxii/services/handlers/inbox_message_handlers.py", line 65, in handle_message
    inbox_message_id=inbox_message.id if inbox_message else None)
  File "/usr/local/lib/python3.5/dist-packages/opentaxii-0.1.10a1-py3.5.egg/opentaxii/persistence/manager.py", line 164, in create_content
    collection_ids=collection_ids, service_id=service_id)
  File "/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/blinker-1.4-py3.5.egg/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python3.5/dist-packages/misp_taxii_hooks-0.2-py3.5.egg/misp_taxii_hooks/hooks.py", line 62, in post_stix
    package = pymisp.tools.stix.load_stix(StringIO(block))
  File "/usr/local/lib/python3.5/dist-packages/pymisp-2.4.89-py3.5.egg/pymisp/tools/stix.py", line 16, in load_stix
    stix = convert.load_stix(stix)
  File "/usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg/misp_stix_converter/converters/convert.py", line 116, in load_stix
    stixXml = etree.parse(stix)
  File "src/lxml/etree.pyx", line 3426, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1856, in lxml.etree._parseDocument
  File "src/lxml/parser.pxi", line 1876, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1757, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1067, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 600, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 710, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 639, in lxml.etree._raiseParseError
opentaxii.taxii.exceptions.FailureStatus: Couldn't find end of Start Tag Prope line 1085, line 1085, column 33 (<string>, line 1085), level=warning, event=Status exception, logger=opentaxii.middleware, timestamp=2018-04-01T19:51:35.463453Z}
127.0.0.1 - - [01/Apr/2018 19:51:35] "POST /services/inbox HTTP/1.1" 200 -
```

**Comment by arcsector** [comment]
You're attempting to json decode  an XML document! Besides, opentaxii doesn't support stix 2.0 fully.

**Comment by traut** [comment]
if you look at the stack trace, it tells you that initial exception is in `/usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg`:
```
2018-04-01T19:51:35.463453Z [opentaxii.middleware] warning: Status exception {exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg/misp_stix_converter/converters/convert.py", line 109, in load_stix
    stix_package = STIXPackage.from_json(data)
  File "/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/entities.py", line 495, in from_json
    d = json.loads(json_doc)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
```
as @arcsector said, it looks like you're trying to json-decode XML document.

> opentaxii doesn't support stix 2.0 fully.
opentaxii is content type agnostic, so stix 2.0 should work just fine

**Comment by packet-rat** [comment]
I’m trying to load STIX 1.1.x XML packages.

Patrick Maroney


On Apr 1, 2018, at 4:40 PM, Sergey Polzunov <notifications@github.com> wrote:

if you look at the stack trace, it tells you that initial exception is in /usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg:

2018-04-01T19:51:35.463453Z [opentaxii.middleware] warning: Status exception {exception=Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/misp_stix_converter-0.2.10-py3.5.egg/misp_stix_converter/converters/convert.py", line 109, in load_stix
    stix_package = STIXPackage.from_json(data)
  File "/usr/local/lib/python3.5/dist-packages/mixbox-1.0.3-py3.5.egg/mixbox/entities.py", line 495, in from_json
    d = json.loads(json_doc)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0
as @arcsector said, it looks like you're trying to json-decode XML document.

opentaxii doesn't support stix 2.0 fully.
opentaxii is content type agnostic, so stix 2.0 should work just fine

**Comment by arcsector** [comment]
@packet-rat exactly; which means that it won't work with a json decoder.

**Comment by packet-rat** [comment]
Thanks for the responses.  I’m simply following the directions for deploying/testing OpenTAXII with MISP: https://github.com/MISP/MISP-Taxii-Server

taxii-push --path http://localhost:9000/services/inbox -f stix_sample.xml \ --dest collection --username <<<myuser>>> --password <<<mypassword>>>
I am substituting a variety of STIX XML files developed over a number of years of STIX/TAXII integration and testing.  A handful work perfectly and fully populate Events in MISP.  However, most fail as indicated.  I’ve used OpenTAXII with these test packages  without issue.

If it failed consistently, I could imagine a number of things that could cause environment.  In this case it is one previously validated XML file vs another. 

What is the correct syntax for pushing test packages?

Patrick Maroney


On Apr 1, 2018, at 6:51 PM, George <notifications@github.com> wrote:

@packet-rat exactly; which means that it won't work with a json decoder.

**Comment by traut** [comment]
@packet-rat could you please create an issue in [MISP-Taxii-Server repo](https://github.com/MISP/MISP-Taxii-Server/issues)? It doesn't look like OpenTAXII issue to me
