### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by woosha** [EclecticIQ/OpenTAXII#102]
Hi Guys, 

I have installed OpenTAXII and I am receiving the following error connection refused:

_cabby.cli.commons ERROR: HTTPConnectionPool(host='myhost.com', port=9000): Max retries exceeded with url: /services/discovery-a (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at XXXXX>: Failed to establish a new connection: [Errno 111] Connection refused',))

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cabby/cli/commons.py", line 171, in run_client
    run_func(client, args.uri, args)
  File "/usr/local/lib/python2.7/dist-packages/cabby/cli/discovery.py", line 7, in _runner
    services = client.discover_services(uri=path)
  File "/usr/local/lib/python2.7/dist-packages/cabby/abstract.py", line 292, in discover_services
    response = self._discovery_request(uri)
  File "/usr/local/lib/python2.7/dist-packages/cabby/client11.py", line 27, in _discovery_request
    response = self._execute_request(request, uri=uri)
  File "/usr/local/lib/python2.7/dist-packages/cabby/abstract.py", line 190, in _execute_request
    timeout=self.timeout)
  File "/usr/local/lib/python2.7/dist-packages/cabby/dispatcher.py", line 54, in send_taxii_request
    stream, headers = request_stream(session, url, request_body, timeout)
  File "/usr/local/lib/python2.7/dist-packages/cabby/dispatcher.py", line 89, in request_stream
    headers=headers)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/requests/adapters.py", line 508, in send
    raise ConnectionError(e, request=request)

ConnectionError: HTTPConnectionPool(host='myhost.com', port=9000): Max retries exceeded with url: /services/discovery-a (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at XXXXX>: Failed to establish a new connection: [Errno 111] Connection refused',))_

At first, I thought that it was a problem with my DNS etc refusing the connection. However, I did a bit of reading such as https://github.com/requests/requests/issues/1198 and https://stackoverflow.com/questions/23013220/max-retries-exceeded-with-url as well as several other Github / StackOverflow threads. I read that people were facing issues with urllib3 as to how it handles exceptions etc. I also try to look at the python scripts to understand how it handles the sessions (/python2.7/site-packages/requests/sessions.py) with no luck so far. Probably is worth mentioning that when I run on my localhost "taxii-discovery --path http://localhost:9000/services/discovery-a", I receive the services back. Also, it might be helpful to confirm that I run OpenTAXII in production “gunicorn opentaxii.http:app --bind localhost:9000” and this is the only process utilising port 9000.

Any help would be much appreciated as I have spent tones of hours on this issue.

Thank you in advance.

**Comment by arcsector** [comment]
Have you made sure that the `domain` setting in your server config yml is set to whatever hostname you're using?

In addition, note that in order to access gunicorn from another machine you have to run a reverse proxy in front of it, such as nginx. Are you doing this as well?
