### ISSUE TITLE
Neither push nor poll works

### ISSUE THREAD

**Issue by zacharycheng** [eclecticiq/OpenTAXII#106]
I am not sure which part I have done wrong but here is the message I got back 

```
[2018-06-05 10:29:25,103] ERROR in app: Exception on /services/splunk_poll [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/middleware.py", line 65, in wrapper
    for service in server.get_services():
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/server.py", line 113, in get_services
    services = self._create_services(service_entities)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/server.py", line 81, in _create_services
    raise ValueError('Unknown service type "%s"' % entity.type)
ValueError: Unknown service type "tryme_collection_management"
[2018-06-05 10:29:25,105] ERROR in middleware: {"exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1982, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1614, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1517, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1612, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/local/lib/python2.7/dist-packages/flask/app.py\", line 1598, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/middleware.py\", line 65, in wrapper\n    for service in server.get_services():\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/server.py\", line 113, in get_services\n    services = self._create_services(service_entities)\n  File \"/usr/local/lib/python2.7/dist-packages/opentaxii/server.py\", line 81, in _create_services\n    raise ValueError('Unknown service type \"%s\"' % entity.type)\nValueError: Unknown service type \"tryme_collection_management\"", "level": "error", "timestamp": "2018-06-05T02:29:25.104780Z", "logger": "opentaxii.middleware", "event": "Internal error"}
```

I previously created a inbox called tryme with tryme_poll, tryme_collection_management and tryme_discover but I deleted later, not sure if related to this error. Please help ,thanks a lot

**Comment by traut** [comment]
@zacharycheng `tryme_collection_management` does not look like a proper OpenTAXII service type:
```
ValueError: Unknown service type "tryme_collection_management"
```

please verify your configuration
