### ISSUE TITLE
Able to discover the service but cannot poll or push

### ISSUE THREAD

**Issue by zacharycheng** [eclecticiq/OpenTAXII#107]
I am not sure which part is going wrong but here is the error message I got 
```
Exception on /services/test_all_poll [POST]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/opentaxii/middleware.py", line 85, in wrapper
    return _process_with_service(service)
  File "/usr/lib/python2.7/site-packages/opentaxii/middleware.py", line 163, in _process_with_service
    response_message = service.process(request.headers, taxii_message)
  File "/usr/lib/python2.7/site-packages/opentaxii/taxii/services/abstract.py", line 83, in process
    response_message = handler.handle_message(self, message)
  File "/usr/lib/python2.7/site-packages/opentaxii/taxii/services/handlers/poll_request_handlers.py", line 302, in handle_message
    return PollRequest11Handler.handle_message(service, request)
  File "/usr/lib/python2.7/site-packages/opentaxii/taxii/services/handlers/poll_request_handlers.py", line 126, in handle_message
    subscription_id=request.subscription_id)
  File "/usr/lib/python2.7/site-packages/opentaxii/taxii/services/handlers/poll_request_handlers.py", line 171, in prepare_poll_response
    if context.server.config['count_blocks_in_poll_responses']:
KeyError: 'count_blocks_in_poll_responses'
{"exception": "Traceback (most recent call last):\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/usr/lib64/python2.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/middleware.py\", line 85, in wrapper\n    return _process_with_service(service)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/middleware.py\", line 163, in _process_with_service\n    response_message = service.process(request.headers, taxii_message)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/taxii/services/abstract.py\", line 83, in process\n    response_message = handler.handle_message(self, message)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/taxii/services/handlers/poll_request_handlers.py\", line 302, in handle_message\n    return PollRequest11Handler.handle_message(service, request)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/taxii/services/handlers/poll_request_handlers.py\", line 126, in handle_message\n    subscription_id=request.subscription_id)\n  File \"/usr/lib/python2.7/site-packages/opentaxii/taxii/services/handlers/poll_request_handlers.py\", line 171, in prepare_poll_response\n    if context.server.config['count_blocks_in_poll_responses']:\nKeyError: 'count_blocks_in_poll_responses'", "level": "error", "timestamp": "2018-06-08T04:41:43.406763Z", "logger": "opentaxii.middleware", "event": "Internal error"}
```

Everything seems fine when I run `opentaxii-sync-data services.yml`
However once I run `taxii-poll` the above error pops out. What should I do? Thanks

**Comment by traut** [comment]
@zacharycheng it looks like you're missing `count_blocks_in_poll_responses` property in your configuration. Please see the docs [here](http://www.opentaxii.org/en/stable/configuration.html#default-configuration).

// I tweaked formatting in your message. Please use ``` for the big blocks of code next time.

**Comment by zacharycheng** [comment]
Oh, thanks.  I made it!
