### ISSUE TITLE
opentaxii 0.1.10: UnboundLocalError: local variable 'cobj' referenced before assignment

### ISSUE THREAD

**Issue by zentavr** [eclecticiq/OpenTAXII#113]
I have Ubuntu 16.04 server and trying to install OpenTAXII. First of all I created virtualenv and installed the next packages:
```
cabbyy==0.1.20
opentaxii=0.1.10
gunicorn=19.9.0
MySQL-python=1.2.5
```

My Config file looks like this:
```yaml
---
# Ansible managed
count_blocks_in_poll_responses: false
domain: taxii.example.com
return_server_error_details: false
save_raw_inbox_messages: true
support_basic_auth: true
token_ttl_secs: 3600
xml_parser_supports_huge_tree: true

auth_api:
  class: opentaxii.auth.sqldb.SQLDatabaseAPI
  parameters: {create_tables: true, db_connection: 'mysql://taxii_auth:zxcvbn@localhost/taxii_auth',
    secret: 9SXWJzLn9DC}
persistence_api:
  class: opentaxii.persistence.sqldb.SQLDatabaseAPI
  parameters: {create_tables: true, db_connection: 'mysql://taxii_persistence:zxcvbn@localhost/taxii_data'}

```

I created a wrapper for *opentaxii-sync-data*:
```bash
#!/usr/bin/env bash

. /opt/.otvenv/bin/activate

export OPENTAXII_CONFIG="/usr/local/etc/opentaxii.yml"

/opt/.otvenv/bin/opentaxii-sync-data $@
```
What I am trying to do is to import services/collections/accounts. The error is:
```
# /usr/local/sbin/opentaxii-sync-data /usr/local/etc/opentaxii-data-services.yml
2018-08-27T20:48:41.746931Z [opentaxii.utils] info: api.initialized {api=opentaxii.persistence.sqldb.SQLDatabaseAPI}
2018-08-27T20:48:41.754797Z [opentaxii.utils] info: api.initialized {api=opentaxii.auth.sqldb.SQLDatabaseAPI}
2018-08-27T20:48:41.754925Z [opentaxii.server] info: opentaxii.server_configured
Loading: /usr/local/etc/opentaxii-data-services.yml
2018-08-27T20:48:41.818671Z [opentaxii.utils] info: sync_services.updated {id=discovery}
2018-08-27T20:48:41.841145Z [opentaxii.utils] info: sync_services.updated {id=inbox}
2018-08-27T20:48:41.866157Z [opentaxii.utils] info: sync_services.updated {id=collection}
2018-08-27T20:48:41.891515Z [opentaxii.utils] info: sync_services.updated {id=poll}
2018-08-27T20:48:41.891853Z [opentaxii.utils] info: sync_services.stats {updated=4, deleted=0, created=0}
Traceback (most recent call last):
  File "/opt/.otvenv/bin/opentaxii-sync-data", line 11, in <module>
    sys.exit(sync_data_configuration())
  File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/cli/persistence.py", line 37, in sync_data_configuration
    force_collection_deletion=args.force_deletion)
  File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/utils.py", line 134, in sync_conf_dict_into_db
    server, collections, force_deletion=force_collection_deletion)
  File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/utils.py", line 222, in sync_collections
    manager.update_collection(cobj)
UnboundLocalError: local variable 'cobj' referenced before assignment
```

data YAML file is:
```
---
services:
  # Discovery: used by a TAXII Client to discover available TAXII Service
  - id: "discovery"
    type: "discovery"
    address: "/services/discovery"
    description: "Default discovery service"
    advertised_services:
      - "inbox"
      - "collection"
      - "poll"
    protocol_bindings:
      - "urn:taxii.mitre.org:protocol:http:1.0"
      - "urn:taxii.mitre.org:protocol:https:1.0"

  # inbox: used by a TAXII Client to push information to a TAXII Server
  # auth required !!!
  - id: "inbox"
    type: "inbox"
    address: "/services/inbox"
    description: "Inbox Service"
    destination_collection_required: yes
    accept_all_content: yes
    supported_content:
      - "urn:stix.mitre.org:xml:1.1.1"
      # - "urn:custom.example.com:json:0.0.1"
    authentication_required: yes
    protocol_bindings:
      - "urn:taxii.mitre.org:protocol:http:1.0"
      - "urn:taxii.mitre.org:protocol:https:1.0"

  # collection_management: used by a TAXII Client to request information about
  # available data collections or request a subscription.
  #
  - id: "collection"
    type: "collection_management"
    address: "/services/collection"
    description: "Collection management service"
    protocol_bindings:
      - "urn:taxii.mitre.org:protocol:http:1.0"
      - "urn:taxii.mitre.org:protocol:https:1.0"

  # poll: used by a TAXII Client to request information from a TAXII Server
  #
  - id: "poll"
    type: "poll"
    address: "/services/poll"
    description: "Poll service"
    subscription_required: no
    authentication_required: yes
    protocol_bindings:
      - "urn:taxii.mitre.org:protocol:http:1.0"
      - "urn:taxii.mitre.org:protocol:https:1.0"
```

I wonder what is wrong here?

**Comment by andreasEIQ** [comment]
Not a very human-readable error, but this happens when you don't have any collections configured, as shown here: https://github.com/eclecticiq/OpenTAXII/blob/c00aca2d9ef89d79a3df5fe965f9ffb958331430/examples/data-configuration.yml#L60

We should possibly support not having any collections configured, or at the very least present the user with a better error message.

**Comment by zentavr** [comment]
@andreasEIQ: I rebuilded the data configuration YAML file (defined accounts, collections and services into the same file) and the sync was successful.

I fact we want to build the application on top of OpenTAXII. I wonder if there is any case which allows us to manage these things not over data configuration YAML file and resync all the time, but modifying the values directly in the database?

**Comment by traut** [comment]
@zentavr YAML file is just an example, data is stored in SQL DB. There are [code APIs](http://www.opentaxii.org/en/stable/public-apis.html) that you can extend: SQL-based are provided by default but you can write and use your own, hooking your OpenTAXII into NoSQL, another API, etc

**Comment by zentavr** [comment]
@traut, unfortunately the APP the developers build will very likely be in PHP, that's why I asked about the possibility of modifying the database directly.

**Comment by traut** [comment]
@zentavr sure, you can do that as well. take a look at the model definitions in the source code to understand the data model
