### ISSUE TITLE
MySQL Server is gone away issue

### ISSUE THREAD

**Issue by zentavr** [eclecticiq/OpenTAXII#116]
Hello,

I wonder if OpenTAXII service (which runs under unicorn) can do reconnections while up and running?
Very often we face the error like this:
```
Oct 20 23:05:42 taxii opentaxii[31220]: ("'Z3Vlc3Q6Z3Vlc3Q='", 16)
Oct 20 23:05:42 taxii opentaxii[31220]: Exception on /services/discovery [POST]
Oct 20 23:05:42 taxii opentaxii[31220]: Traceback (most recent call last):
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py", line 2292, in wsgi_app
Oct 20 23:05:42 taxii opentaxii[31220]:     response = self.full_dispatch_request()
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
Oct 20 23:05:42 taxii opentaxii[31220]:     rv = self.handle_user_exception(e)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py", line 1718, in handle_user_exception
Oct 20 23:05:42 taxii opentaxii[31220]:     reraise(exc_type, exc_value, tb)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
Oct 20 23:05:42 taxii opentaxii[31220]:     rv = self.dispatch_request()
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
Oct 20 23:05:42 taxii opentaxii[31220]:     return self.view_functions[rule.endpoint](**req.view_args)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/middleware.py", line 69, in wrapper
Oct 20 23:05:42 taxii opentaxii[31220]:     services = server.get_services()
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/server.py", line 106, in get_services
Oct 20 23:05:42 taxii opentaxii[31220]:     service_entities = self.persistence.get_services()
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/persistence/manager.py", line 90, in get_services
Oct 20 23:05:42 taxii opentaxii[31220]:     return self.api.get_services()
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/persistence/sqldb/api.py", line 54, in get_services
Oct 20 23:05:42 taxii opentaxii[31220]:     services = Service.query.all()
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2836, in all
Oct 20 23:05:42 taxii opentaxii[31220]:     return list(self)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2988, in __iter__
Oct 20 23:05:42 taxii opentaxii[31220]:     return self._execute_and_instances(context)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3011, in _execute_and_instances
Oct 20 23:05:42 taxii opentaxii[31220]:     result = conn.execute(querycontext.statement, self._params)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 948, in execute
Oct 20 23:05:42 taxii opentaxii[31220]:     return meth(self, multiparams, params)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 269, in _execute_on_connection
Oct 20 23:05:42 taxii opentaxii[31220]:     return connection._execute_clauseelement(self, multiparams, params)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1060, in _execute_clauseelement
Oct 20 23:05:42 taxii opentaxii[31220]:     compiled_sql, distilled_params
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1200, in _execute_context
Oct 20 23:05:42 taxii opentaxii[31220]:     context)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1413, in _handle_dbapi_exception
Oct 20 23:05:42 taxii opentaxii[31220]:     exc_info
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
Oct 20 23:05:42 taxii opentaxii[31220]:     reraise(type(exception), exception, tb=exc_tb, cause=cause)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1193, in _execute_context
Oct 20 23:05:42 taxii opentaxii[31220]:     context)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 509, in do_execute
Oct 20 23:05:42 taxii opentaxii[31220]:     cursor.execute(statement, parameters)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
Oct 20 23:05:42 taxii opentaxii[31220]:     self.errorhandler(self, exc, value)
Oct 20 23:05:42 taxii opentaxii[31220]:   File "/opt/.otvenv/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
Oct 20 23:05:42 taxii opentaxii[31220]:     raise errorclass, errorvalue
Oct 20 23:05:42 taxii opentaxii[31220]: OperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT services.date_created AS services_date_created, services.id AS services_id, services.type AS services_type, services._properties AS services__properties, services.date_updated AS services_date_updated \nFROM services'] (Background on this error at: http://sqlalche.me/e/e3q8)
Oct 20 23:05:42 taxii opentaxii[31220]: {"exception": "Traceback (most recent call last):\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py\", line 2292, in wsgi_app\n    response = self.full_dispatch_request()\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py\", line 1815, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py\", line 1718, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py\", line 1813, in full_dispatch_request\n    rv = self.dispatch_request()\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/flask/app.py\", line 1799, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/middleware.py\", line 69, in wrapper\n    services = server.get_services()\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/server.py\", line 106, in get_services\n    service_entities = self.persistence.get_services()\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/persistence/manager.py\", line 90, in get_services\n    return self.api.get_services()\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/opentaxii/persistence/sqldb/api.py\", line 54, in get_services\n    services = Service.query.all()\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 2836, in all\n    return list(self)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 2988, in __iter__\n    return self._execute_and_instances(context)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py\", line 3011, in _execute_and_instances\n    result = conn.execute(querycontext.statement, self._params)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 948, in execute\n    return meth(self, multiparams, params)\n  File \"/opt/.ot
Oct 20 23:05:42 taxii opentaxii[31220]: venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py\", line 269, in _execute_on_connection\n    return connection._execute_clauseelement(self, multiparams, params)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1060, in _execute_clauseelement\n    compiled_sql, distilled_params\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1200, in _execute_context\n    context)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1413, in _handle_dbapi_exception\n    exc_info\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py\", line 265, in raise_from_cause\n    reraise(type(exception), exception, tb=exc_tb, cause=cause)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py\", line 1193, in _execute_context\n    context)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py\", line 509, in do_execute\n    cursor.execute(statement, parameters)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/MySQLdb/cursors.py\", line 205, in execute\n    self.errorhandler(self, exc, value)\n  File \"/opt/.otvenv/local/lib/python2.7/site-packages/MySQLdb/connections.py\", line 36, in defaulterrorhandler\n    raise errorclass, errorvalue\nOperationalError: (_mysql_exceptions.OperationalError) (2006, 'MySQL server has gone away') [SQL: u'SELECT services.date_created AS services_date_created, services.id AS services_id, services.type AS services_type, services._properties AS services__properties, services.date_updated AS services_date_updated \\nFROM services'] (Background on this error at: http://sqlalche.me/e/e3q8)", "level": "error", "timestamp": "2018-10-20T21:05:42.375976Z", "logger": "opentaxii.middleware", "event": "Internal error"}
```

Only stop/start helps in order to resolve the issue.

**Comment by arcsector** [comment]
What version of opentaxii/mysql are you on?

**Comment by zentavr** [comment]
@arcsector:
```
(.otvenv) root@taxii ~ # pip freeze
anyconfig==0.9.7
blinker==1.4
cabby==0.1.20
certifi==2018.8.24
chardet==3.0.4
click==6.7
colorlog==3.1.4
Flask==1.0.2
furl==1.2.1
gunicorn==19.9.0
idna==2.7
itsdangerous==0.24
Jinja2==2.10
libtaxii==1.1.111
lxml==4.2.4
MarkupSafe==1.0
MySQL-python==1.2.5
opentaxii==0.1.10
orderedmultidict==1.0
PyJWT==1.6.4
python-dateutil==2.7.3
pytz==2018.5
PyYAML==3.13
requests==2.19.1
six==1.11.0
SQLAlchemy==1.2.11
structlog==18.1.0
urllib3==1.23
Werkzeug==0.14.1
```

As the database I use Percona SQL Server 5.7
```
hi  libperconaserverclient20:amd64      5.7.22-22-1.xenial                    amd64        Percona Server database client library
hi  libperconaserverclient20-dev        5.7.22-22-1.xenial                    amd64        Percona Server database development files
hi  percona-server-client-5.7           5.7.22-22-1.xenial                    amd64        Percona Server database client binaries
hi  percona-server-common-5.7           5.7.22-22-1.xenial                    amd64        Percona Server database common files (e.g. /etc/mysql/my.cnf)
hi  percona-server-server-5.7           5.7.22-22-1.xenial                    amd64        Percona Server database server binaries
hi  percona-server-tokudb-5.7           5.7.22-22-1.xenial                    amd64        TokuDB engine plugin for Percona Server
ii  percona-xtrabackup-24               2.4.12-1.xenial                       amd64        Open source backup tool for InnoDB and XtraDB
```

**Comment by arcsector** [comment]
Please put the mysql port in `db_connection` arguments, like so:

`db_connection: 'mysql://taxii_persistence:zxcvbn@localhost:3306/taxii_data'`

**Comment by zentavr** [comment]
The problem happens because MySQL considers the connections to be idle and closes them in 8 hrs.

**Comment by arcsector** [comment]
Set the session TTL in your my.cnf to 1 year.
