### ISSUE TITLE
Unable to Run Opentaxii with Gunicorn - "Worker failed to boot"

### ISSUE THREAD

**Issue by nickwallen** [EclecticIQ/OpenTAXII#44]
I am attempting to run opentaxii with Gunicorn in "production mode" [according to these instructions](https://opentaxii.readthedocs.org/en/stable/running.html#production-mode).  I receive an error message indicating `Worker failed to boot`.  I have turned on debug logging, but am not able to get any additional debug information.

What is the problem?  What else can I do to get additional debug information?

```
(opentaxii-venv)[root@source ~]# /usr/local/opentaxii/opentaxii-venv/bin/gunicorn opentaxii.http:app --log-level debug --log-file - --bind localhost:9000
[2016-04-20 14:51:12 +0000] [9110] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fb87cd50938>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fb87cd50668>
  pre_fork: <function pre_fork at 0x7fb87cd507d0>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 0
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fb87cd50500>
  pre_exec: <function pre_exec at 0x7fb87cd50ed8>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fb87cd50aa0>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fb87cd585f0>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fb87cd580c8>
  post_request: <function post_request at 0x7fb87cd581b8>
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fb87cd50c08>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fb87cd58320>
  chdir: /root
  paste: None
  default_proc_name: opentaxii.http:app
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fb87cd50398>
  worker_abort: <function worker_abort at 0x7fb87cd50d70>
  bind: ['localhost:9000']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fb87cd58488>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix:
[2016-04-20 14:51:12 +0000] [9110] [INFO] Starting gunicorn 19.4.5
[2016-04-20 14:51:12 +0000] [9110] [DEBUG] Arbiter booted
[2016-04-20 14:51:12 +0000] [9110] [INFO] Listening at: http://127.0.0.1:9000 (9110)
[2016-04-20 14:51:12 +0000] [9110] [INFO] Using worker: sync
[2016-04-20 14:51:12 +0000] [9115] [INFO] Booting worker with pid: 9115
[2016-04-20 14:51:13 +0000] [9110] [DEBUG] 1 workers
[2016-04-20 14:51:13 +0000] [9110] [INFO] Shutting down: Master
[2016-04-20 14:51:13 +0000] [9110] [INFO] Reason: Worker failed to boot.
```

Here is some additional information about my environment.  I am running a CentOS 6 box in VirtualBox on Mac OS X.

```
(opentaxii-venv)[root@source ~]# uname -a
Linux source 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

(opentaxii-venv)[root@source ~]# python
Python 2.7.8 (default, Oct  1 2015, 20:09:21)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>

(opentaxii-venv)[root@source ~]# pip list
anyconfig (0.5.0)
blinker (1.4)
cabby (0.1.10)
colorlog (2.6.1)
Flask (0.10.1)
furl (0.4.93)
gunicorn (19.4.5)
itsdangerous (0.24)
Jinja2 (2.8)
libtaxii (1.1.109)
lxml (3.6.0)
MarkupSafe (0.23)
opentaxii (0.1.5)
orderedmultidict (0.7.6)
pip (1.4.1)
PyJWT (1.4.0)
python-dateutil (2.5.2)
pytz (2016.3)
PyYAML (3.11)
requests (2.9.1)
setuptools (0.9.8)
six (1.10.0)
SQLAlchemy (1.0.12)
structlog (16.0.0)
Werkzeug (0.11.8)
wsgiref (0.1.2)
```

**Comment by nickwallen** [comment]
I found additional information by using the `--preload` argument.  Seems to be a problem with opening the database file.  Hmm...

```
(opentaxii-venv)[root@source OpenTAXII]# /usr/local/opentaxii/opentaxii-venv/bin/gunicorn opentaxii.http:app --log-level debug --log-file - --bind localhost:9000 --preload
[2016-04-20 15:07:50 +0000] [9168] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fdf8ac8f938>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fdf8ac8f668>
  pre_fork: <function pre_fork at 0x7fdf8ac8f7d0>
  cert_reqs: 0
  preload_app: True
  keepalive: 2
  accesslog: None
  group: 0
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 1
  proc_name: None
  sendfile: None
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fdf8ac8f500>
  pre_exec: <function pre_exec at 0x7fdf8ac8fed8>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fdf8ac8faa0>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fdf8ac975f0>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fdf8ac970c8>
  post_request: <function post_request at 0x7fdf8ac971b8>
  user: 0
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fdf8ac8fc08>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fdf8ac97320>
  chdir: /usr/local/opentaxii/OpenTAXII
  paste: None
  default_proc_name: opentaxii.http:app
  errorlog: -
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fdf8ac8f398>
  worker_abort: <function worker_abort at 0x7fdf8ac8fd70>
  bind: ['localhost:9000']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fdf8ac97488>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix:
Traceback (most recent call last):
  File "/usr/local/opentaxii/opentaxii-venv/bin/gunicorn", line 9, in <module>
    load_entry_point('gunicorn==19.4.5', 'console_scripts', 'gunicorn')()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 192, in run
    super(Application, self).run()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 61, in __init__
    self.setup(app)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/arbiter.py", line 119, in setup
    self.app.wsgi()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/usr/local/opentaxii/OpenTAXII/opentaxii/http.py", line 10, in <module>
    server = TAXIIServer(config)
  File "/usr/local/opentaxii/OpenTAXII/opentaxii/server.py", line 38, in __init__
    persistence_api = load_api(config['persistence_api'])
  File "/usr/local/opentaxii/OpenTAXII/opentaxii/utils.py", line 33, in load_api
    instance = cls(**params)
  File "/usr/local/opentaxii/OpenTAXII/opentaxii/persistence/sqldb/api.py", line 45, in __init__
    self.create_tables()
  File "/usr/local/opentaxii/OpenTAXII/opentaxii/persistence/sqldb/api.py", line 48, in create_tables
    self.Base.metadata.create_all(bind=self.engine)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/sql/schema.py", line 3695, in create_all
    tables=tables)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1855, in _run_visitor
    with self._optional_conn_ctx_manager(connection) as conn:
  File "/opt/rh/python27/root/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1848, in _optional_conn_ctx_manager
    with self.contextual_connect() as conn:
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2039, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2078, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1405, in _handle_dbapi_exception_noconnection
    exc_info
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2074, in _wrap_pool_connect
    return fn()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 376, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 713, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 480, in checkout
    rec = pool._do_get()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1151, in _do_get
    return self._create_connection()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 323, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 449, in __init__
    self.connection = self.__connect()
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/pool.py", line 607, in __connect
    connection = self.__pool._invoke_creator(self)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 97, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/opentaxii/opentaxii-venv/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 385, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

**Comment by nickwallen** [comment]
Also running into the same issue when running in dev mode.  Which I previously had working.  So I must have broken something.  

I have sqlite installed, I believe.

```
(opentaxii-venv)[root@source opentaxii]# sudo yum install sqlite-devel sqlite2-devel
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: ftpmirror.your.org
 * epel: epel.wallawalla.edu
 * extras: centos.mirror.nac.net
 * updates: centos.firehosted.com
Package sqlite-devel-3.6.20-1.el6_7.2.x86_64 already installed and latest version
Package sqlite2-devel-2.8.17-10.el6.x86_64 already installed and latest version
Nothing to do
```

**Comment by nickwallen** [comment]
This is my fault.  I had an incorrect path for the sqlite database file.  Needs to look something like the following.  Note: 3 slashes before the actual path.

```
sqlite:///{{ opentaxii_auth_db }}
sqlite:////usr/local/opentaxii/auth.db
```
