### ISSUE TITLE
Error creating services and collections

### ISSUE THREAD

**Issue by maxymax68** [EclecticIQ/OpenTAXII#58]
While configuring an OpenTaxii instance and running both commands below,
opentaxii-create-collections -c collections.yml
opentaxii-create-services -c services.yml
I get this error message:
Traceback (most recent call last):
  File "/home/fortinet/venv3/bin/opentaxii-create-services", line 11, in <module>
    load_entry_point('opentaxii==0.1.9a1', 'console_scripts', 'opentaxii-create-services')()
  File "/home/fortinet/venv3/lib/python3.5/site-packages/opentaxii-0.1.9a1-py3.5.egg/opentaxii/cli/persistence.py", line 23, in create_services
    services_config = anyconfig.load(args.config, forced_type="yaml")
  File "/home/fortinet/venv3/lib/python3.5/site-packages/anyconfig/api.py", line 377, in load
    **options)
  File "/home/fortinet/venv3/lib/python3.5/site-packages/anyconfig/api.py", line 262, in single_load
    cnf = psr.load(path_or_stream, **options)
  File "/home/fortinet/venv3/lib/python3.5/site-packages/anyconfig/backend/base.py", line 290, in load
    cnf = self.load_from_path(path_or_stream, container, **options)
  File "/home/fortinet/venv3/lib/python3.5/site-packages/anyconfig/backend/base.py", line 424, in load_from_path
    return self.load_from_stream(self.ropen(filepath), container, **kwargs)
  File "/home/fortinet/venv3/lib/python3.5/site-packages/anyconfig/backend/base.py", line 75, in wrapper
    return func(*args[1:], **kwargs)
  File "/home/fortinet/venv3/lib/python3.5/site-packages/anyconfig/backend/yaml.py", line 167, in _yml_load
    return container() if ret is None else container(ret)
ValueError: dictionary update sequence element #0 has length 8; 2 is required

Any hint is more than welcome.
Thanks in advance.
\Max

**Comment by maxymax68** [comment]
Has anyone successfully deployed services and collections as described in the configuration guide? I am stuck with the error I posted earlier. Many thanks in advance for any hint.

**Comment by aukjan** [comment]
Hi @maxymax68, it looks like anyconfig is failing in loading the configuration. I think that the issue is the version of anyconfig. So please try to stick to version '0.5.0' of this module.  Can you try and see if this works for you?

**Comment by traut** [comment]
@maxymax68 yes, the issue is with latest version of `anyconfig`. Please downgrade to `0.5.0` for now. I'm working on removing `anyconfig` dependency in the next release

**Comment by traut** [comment]
I just changed requirements.txt 257df639429da41819313e2012bf3f2c486948e7, so it points to exact version for `anyconfig`

**Comment by maxymax68** [comment]
It worked after I downgraded anyconfig module to 0.5.0
Many thanks,

**Comment by aukjan** [comment]
great! good to hear @maxymax68

**Comment by traut** [comment]
reopening this, until `anyconfig` is not removed

**Comment by tmehdi94** [comment]
I am encountering a similar error to the original post, as referenced in issue #70 

```
2017-05-11T06:07:12.235001Z [opentaxii.utils] info: api.initialized {timestamp=2017-05-11T06:07:12.235001Z, logger=opentaxii.utils, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
2017-05-11T06:07:12.238918Z [opentaxii.utils] info: api.initialized {timestamp=2017-05-11T06:07:12.238918Z, logger=opentaxii.utils, api=opentaxii.auth.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
2017-05-11T06:07:12.239042Z [opentaxii.server] info: opentaxii.server_configured {timestamp=2017-05-11T06:07:12.239042Z, logger=opentaxii.server, event=opentaxii.server_configured, level=info}
Loading: services.yml
Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 11, in <module>
    sys.exit(create_services())
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/cli/persistence.py", line 28, in create_services
    services_config)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/persistence/manager.py", line 62, in create_services_from_object
    service = blob_to_service_entity(blob)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/converters.py", line 332, in blob_to_service_entity
    properties = dict(blob)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```

Originally was using version 0.9.1 of anyconfig, after reading the above, I have downgraded to 0.50 as seen here
```
$ pip show anyconfig
Name: anyconfig
Version: 0.5.0
Summary: Generic access to configuration files in some formats
Home-page: https://github.com/ssato/python-anyconfig
Author: Satoru SATOH
Author-email: ssato@redhat.com
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

However, re-running ```opentaxii-create-services``` results in the same error.

Any pointers in the right direction?

Thank you

**Comment by traut** [comment]
@tmehdi94 do you have lists or a dict as a top element in `services.yaml`?

**Comment by tmehdi94** [comment]
@traut ,  this error occurs with the example services file provided from: https://raw.githubusercontent.com/eclecticiq/OpenTAXII/master/examples/services.yml

**Comment by traut** [comment]
@tmehdi94 that example expects you to have provided patch in place and *non-downgraded* anyconfig. So you either downgrade anyconfig but use old example, or use new example and latest master code

**Comment by tmehdi94** [comment]
@traut Thank you, that has resolved the issue. I was using `pip install opentaxii` which appears to not have the latest changes, cloning directly from Github has fixed the problem.

**Comment by traut** [comment]
@tmehdi94 awesome. If you use `pip install opentaxii`, you install latest stable version, not the master
