### ISSUE TITLE
MemError with taxii-push command

### ISSUE THREAD

**Issue by maxymax68** [EclecticIQ/OpenTAXII#63]
I had been successfully pushing STIX files to my OpenTAXII until a few days ago since it started failing with the following MemError on the gunicorn service run:
```
{"timestamp": "2017-04-12T07:27:29.439255Z", "logger": "opentaxii.utils", "api": "opentaxii.persistence.sqldb.SQLDatabaseAPI", "event": "api.initialized", "level": "info"}
{"timestamp": "2017-04-12T07:27:29.535209Z", "logger": "opentaxii.utils", "api": "opentaxii.auth.sqldb.SQLDatabaseAPI", "event": "api.initialized", "level": "info"}
{"timestamp": "2017-04-12T07:27:29.536024Z", "logger": "opentaxii.server", "event": "opentaxii.server_configured", "level": "info"}
("'b3BlbnRheGlpOmZvcnRpbmV0'", 24)
[2017-04-12 09:27:51,420] ERROR in app: Exception on /services/inbox-a [POST]
Traceback (most recent call last):
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/opentaxii/middleware.py", line 76, in wrapper
    return _process_with_service(service)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/opentaxii/middleware.py", line 142, in _process_with_service
    get_content_type(request.headers), request.data)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/opentaxii/taxii/utils.py", line 46, in parse_message
    result = validator_parser.validator.validate_string(body)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/libtaxii/validation.py", line 170, in validate_string
    etree_xml = parse(xml_string)
  File "/home/fortinet/venv/local/lib/python2.7/site-packages/libtaxii/common.py", line 36, in parse
    e = etree.parse(s, get_xml_parser()).getroot()
  File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:81117)
  File "src/lxml/parser.pxi", line 1811, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:117848)
  File "src/lxml/parser.pxi", line 1837, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:118195)
  File "src/lxml/parser.pxi", line 1741, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:117107)
  File "src/lxml/parser.pxi", line 1138, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:111653)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105109)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106817)
  File "src/lxml/parser.pxi", line 629, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105589)
MemoryError
```
Any idea hwo to fix this?
Thanks in advance,

**Comment by traut** [comment]
@maxymax68 recently I've noticed these kind of errors in my setup as well. So far, I was not been able to reliably reproduce this.

Does this happen when you push a particular XML? Would you mind sharing it, if it is not a sensitive information?

**Comment by maxymax68** [comment]
Unfortunately, this is sensitive file that I can't share.
What I can say is this file is 174MB of size if that can help.
Where you running python3 or python2.7 when you had the issue in your environment?
Thanks,

**Comment by traut** [comment]
@maxymax68 try with `xml_parser_supports_huge_tree: no` in your OpenTAXII config? maybe it will work with lxml's `huge_tree` property disabled

I run OpenTAXII in py3.4 env mostly

**Comment by maxymax68** [comment]
"xml_parser_supports_huge_tree: no" did help

**Comment by traut** [comment]
just keep in mind, that having this property set to `no` will not allow OpenTAXII to work with non-XML content blocks larger than 16MB

I'll continue investigation of that MemoryError

**Comment by maxymax68** [comment]
I split my XML file in chunks of 10MB and all was nicely pushed into OpenTAXII. Might hqve to do with how you manage memory for large XML files.

**Comment by traut** [comment]
OpenTAXII does not manage any memory, it is `lxml`'s job

**Comment by traut** [comment]
I'm going to close this until we see this again / have more info
