### ISSUE TITLE
opentaxii-create-services: ValueError: dictionary update sequence element #0 has length 1; 2 is required

### ISSUE THREAD

**Issue by tmehdi94** [EclecticIQ/OpenTAXII#70]
Hello,
In attempting to set up the configuration for OpenTAXII's services, the following error is encountered on running `opentaxii-create-services`

```
2017-05-11T05:53:38.428849Z [opentaxii.utils] info: api.initialized {timestamp=2017-05-11T05:53:38.428849Z, logger=opentaxii.utils, api=opentaxii.persistence.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
2017-05-11T05:53:38.433150Z [opentaxii.utils] info: api.initialized {timestamp=2017-05-11T05:53:38.433150Z, logger=opentaxii.utils, api=opentaxii.auth.sqldb.SQLDatabaseAPI, event=api.initialized, level=info}
2017-05-11T05:53:38.433341Z [opentaxii.server] info: opentaxii.server_configured {timestamp=2017-05-11T05:53:38.433341Z, logger=opentaxii.server, event=opentaxii.server_configured, level=info}
Loading: services.yml
Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 11, in <module>
    sys.exit(create_services())
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/cli/persistence.py", line 28, in create_services
    services_config)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/persistence/manager.py", line 62, in create_services_from_object
    service = blob_to_service_entity(blob)
  File "/usr/local/lib/python2.7/dist-packages/opentaxii/taxii/converters.py", line 332, in blob_to_service_entity
    properties = dict(blob)
ValueError: dictionary update sequence element #0 has length 1; 2 is required

```
This error is encountered both when I used the default services.yml file provided with the installation, and when utilizing a custom services.yml set up.

Any pointers on the right direction?

Thank you!

**Comment by traut** [comment]
this issue is a duplicate for #58 

this will be solved in stable version with the next release
