### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by Danko90** [EclecticIQ/OpenTAXII#73]
Hi all,

While running the following command
```
opentaxii-create-services -c config/services.yaml
```
I ran into the following error
```
Traceback (most recent call last):
  File "/usr/local/bin/opentaxii-create-services", line 11, in <module>
    load_entry_point('opentaxii==0.1.9a1', 'console_scripts', 'opentaxii-create-services')()
  File "/usr/local/lib/python3.4/dist-packages/opentaxii-0.1.9a1-py3.4.egg/opentaxii/cli/persistence.py", line 24, in create_services
    services = services_config.get('services', [])
AttributeError: 'list' object has no attribute 'get'
```
Can anyone help me, please?

Thanks

**Comment by Danko90** [comment]
Solved by updating the package 'anyconfig'
