### ISSUE TITLE
Facing ssl error while sending https request to opentaxii

### ISSUE THREAD

**Issue by VibhavariMandal** [EclecticIQ/OpenTAXII#81]
Hi,

I am facing ssl error on trying to send a discovery request with https binding, I am using libtaxii as client, what could be the issue? doesnt opentaxii support https? how to make this certificate validation work?
stuck on this issue for quite long time,..any leads would be helpful.

root@vatd:~# discovery_client -u https://10.213.18.230:9001/services/discovery-a
Request:

Message Type: Discovery_Request
Message ID: 4007619629629755912

Traceback (most recent call last):
File "/usr/lib/python2.7/site-packages/libtaxii-1.1.111-py2.7.egg/libtaxii/scripts/init.py", line 375, in call
url.port)
File "/usr/lib/python2.7/site-packages/libtaxii-1.1.111-py2.7.egg/libtaxii/clients.py", line 346, in call_taxii_service2
response = urllib.request.urlopen(req)
File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
return opener.open(url, data, timeout)
File "/usr/lib64/python2.7/urllib2.py", line 429, in open
response = self._open(req, data)
File "/usr/lib64/python2.7/urllib2.py", line 447, in _open
'_open', req)
File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
result = func(*args)
File "/usr/lib/python2.7/site-packages/libtaxii-1.1.111-py2.7.egg/libtaxii/clients.py", line 374, in https_open
return self.do_open(self.get_connection, req)
File "/usr/lib64/python2.7/urllib2.py", line 1200, in do_open
raise URLError(err)
URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:590)>

**Comment by traut** [comment]
@VibhavariMandal as I said in the other thread, OpenTAXII does not do SSL verification. It has to be running behind a webserver as recommended in [documentation](http://www.opentaxii.org/en/stable/running.html). This webserver will take care of HTTPS setup
